plugins {
    id "fabric-loom" version "1.14-SNAPSHOT"
}

def targets = [
    "1.21.4": [
        version: "1.21.4",
        yarn: "1.21.4+build.7",
        loader: "0.16.9",
        baritone: "1.13.1"
    ],
    "1.21.11": [
        version: "1.21.11",
        yarn: "1.21.11+build.3",
        loader: "0.18.2",
        baritone: "1.17.0"
    ]
]

def client = findProperty("mc") ?: "1.21.4"
def target = targets[client]

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main {
        java {
            srcDirs = ["src/main/java", "src/${client}/java"]
            exclude "dev/**"
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = "Meteor Dev Releases"
        url = "https://maven.meteordev.org/releases"
    }

    maven {
        name = "Meteor Dev Snapshots"
        url = "https://maven.meteordev.org/snapshots"
    }
}

dependencies {
    // Fabric
    minecraft "com.mojang:minecraft:${target.version}"
    mappings "net.fabricmc:yarn:${target.yarn}:v2"
    modImplementation "net.fabricmc:fabric-loader:${target.loader}"

    // Meteor
    modImplementation "meteordevelopment:meteor-client:${target.version}-SNAPSHOT"

    // Baritone
    modCompileOnly files("libs/baritone-api-fabric-${target.baritone}.jar")

    // XaeroPlus
    modImplementation "maven.modrinth:xaeroplus:2.30.6+fabric-${target.version}"

    // Xaero's World Map
    modImplementation "maven.modrinth:xaeros-world-map:fabric-${target.version}-1.40.10"

    // Xaero's Minimap
    modImplementation "maven.modrinth:xaeros-minimap:fabric-${target.version}-25.3.9"

    // Lambda Events
    modImplementation "net.lenni0451:LambdaEvents:2.4.2"
}

tasks {
    processResources {
        def properties = [
            "version": project.version,
            "mc_version": target.version
        ]

        inputs.properties(properties)
        filteringCharset = "UTF-8"

        filesMatching("fabric.mod.json") {
            expand(properties)
        }
    }

    jar {
        inputs.property("archivesName", project.archives_base_name)

        from("LICENSE") {
            rename { "${it}_${project.archives_base_name}" }
        }
    }

    remapJar {
        archiveFileName =
            "${project.archives_base_name}-${project.mod_version}+${target.version}.jar"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
    options.compilerArgs.add("-Xlint:deprecation")
    options.compilerArgs.add("-Xlint:unchecked")
}
