org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:/Program Files/Zulu/zulu-21

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.7
loader_version=0.16.9

# Mod Properties
mod_version=260825
maven_group=dev.arkieee
archives_base_name=hyperglide

# Dependencies
